export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
      backgroundColor: '#07111f',
      isolation: 'isolate',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      position: 'relative',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      width: 'fit-content',
      marginInline: 'auto',
      padding: { base: '12px 42px 12px 17px', lg: '15px 46px 15px 26px' },
      borderRadius: { base: '18px', lg: '16px' },
      minWidth: { base: 'auto', lg: '60%' },
      maxWidth: { base: '92vw', lg: 'min(760px, 92%)' },
      maxHeight: { base: '30dvh', lg: '34dvh' },
      overflowY: 'auto',
      overflowX: 'hidden',
      overscrollBehavior: 'contain',
      backdropFilter: 'blur(12px)',
      border: '1px solid rgba(255, 255, 255, 0.08)',
      boxShadow: '0 8px 28px rgba(0, 0, 0, 0.22)',
    },
    closeButton: {
      position: 'absolute',
      top: { base: '5px', lg: '8px' },
      right: { base: '5px', lg: '8px' },
      minWidth: { base: '28px', lg: '32px' },
      width: { base: '28px', lg: '32px' },
      height: { base: '28px', lg: '32px' },
      borderRadius: 'full',
      bg: 'transparent',
      color: 'whiteAlpha.700',
      fontSize: { base: '18px', lg: '20px' },
      _hover: { bg: 'whiteAlpha.200', color: 'white' },
      _active: { bg: 'whiteAlpha.300' },
    },
    text: {
      color: 'white',
      fontSize: { base: '16px', lg: '1.5rem' },
      textAlign: { base: 'left', lg: 'center' },
      lineHeight: { base: '1.48', lg: '1.45' },
      whiteSpace: 'pre-wrap',
      overflowWrap: 'anywhere',
      wordBreak: 'break-word',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      // top: '20px',
      // left: '20px',
      zIndex: 2,
      padding: { base: '6px 10px', lg: '8px 16px' },
      borderRadius: '20px',
      fontSize: { base: '11px', lg: '14px' },
      fontWeight: 'medium',
      color: 'white',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        opacity: 0.8,
      },
    },
  },
};
