import { miliTokens } from '@/theme/design-tokens';

export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
      backgroundColor: miliTokens.color.background,
      isolation: 'isolate',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      position: 'relative',
      backgroundColor: miliTokens.color.elevated,
      width: 'fit-content',
      marginInline: 'auto',
      padding: { base: '10px 40px 10px 16px', lg: '15px 46px 15px 26px' },
      borderRadius: { base: miliTokens.radius.lg, lg: miliTokens.radius.lg },
      minWidth: { base: 'auto', lg: '60%' },
      maxWidth: { base: '92vw', lg: 'min(760px, 92%)' },
      maxHeight: { base: '30dvh', lg: '34dvh' },
      overflowY: 'auto',
      overflowX: 'hidden',
      overscrollBehavior: 'contain',
      backdropFilter: miliTokens.blur.card,
      border: '1px solid',
      borderColor: miliTokens.color.border,
      boxShadow: miliTokens.shadow.float,
    },
    closeButton: {
      position: 'absolute',
      top: { base: '5px', lg: '8px' },
      right: { base: '5px', lg: '8px' },
      minWidth: { base: '28px', lg: '32px' },
      width: { base: '28px', lg: '32px' },
      height: { base: '28px', lg: '32px' },
      borderRadius: 'full',
      bg: 'transparent',
      color: 'whiteAlpha.700',
      fontSize: { base: '18px', lg: '20px' },
      _hover: { bg: 'whiteAlpha.200', color: 'white' },
      _active: { bg: 'whiteAlpha.300' },
    },
    text: {
      color: 'white',
      fontSize: { base: '16px', lg: '1.5rem' },
      textAlign: { base: 'left', lg: 'center' },
      lineHeight: { base: '1.48', lg: '1.45' },
      whiteSpace: 'pre-wrap',
      overflowWrap: 'anywhere',
      wordBreak: 'break-word',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      zIndex: 2,
      display: 'inline-flex',
      alignItems: 'center',
      gap: '7px',
      padding: { base: '7px 12px', lg: '8px 14px' },
      borderRadius: miliTokens.radius.pill,
      border: '1px solid',
      fontSize: { base: miliTokens.font.xs, lg: miliTokens.font.sm },
      fontWeight: 'medium',
      color: miliTokens.color.textSecondary,
      transition: 'all 0.2s',
      userSelect: 'none',
      backdropFilter: miliTokens.blur.card,
    },
    dot: {
      width: '7px',
      height: '7px',
      borderRadius: 'full',
      flexShrink: 0,
    },
  },
};
